### ISSUE TITLE
Using lsp-execute-code-action throws error

### ISSUE THREAD

**Issue by Blade6570** [emacs-grammarly/lsp-grammarly#11]
Hi, thank you for this package. After getting the errors from the server, I use `lsp-execute-code-action` to fix the error automatically. Although it fixes the error in the beginning, it throws error as
```
(error "The connected server(s) does not support method workspace/executeCommand.
To find out what capabilities support your server use ‘M-x lsp-describe-session’
and expand the capabilities section")
```
After doing this a few times, the `lsp-execute-code-action` completely stops working and only shows the above message whenever I do M-x `lsp-execute-code-action`.

**Comment by jcs090218** [comment]
Sorry for the late reply!

I wonder what triggers the `lsp-execute-code-action`? I have not thoroughly dig the `lsp-mode` API yet, I think this is the same as #9?

**Comment by Blade6570** [comment]
Hi, 
I do `M-x` `lsp-execute-code-action` on the error on point. It looks like that it is the same as #9. Any plans to fix it in the near future?

**Comment by jcs090218** [comment]
No, not really. I am quite busy with something else. I might have this in lower priority. 😓 Feel free if you want to give it a hand. PR are welcome!

**Comment by vzaliva** [comment]
I am having this issue when clicking on "ignore error". Here is my session capabilities:
```
    `-[-] Capabilities
       |-[X] codeActionProvider: t
       |-[X] hoverProvider: t
       `-[-] textDocumentSync:
          |-[X] change: 2
          `-[X] openClose: t
```

**Comment by vzaliva** [comment]
Setting `lsp-auto-execute-action` to `nil` improves the behaviour. 
It looks like it was picking the first action (ignore) which is not implemented?
I can try to dig into this further. @jcs090218 would you provide some guidance directions?

**Comment by vzaliva** [comment]
I've tracked it down to `lsp--send-request-async` which receives `grammarly.callback` command and arguments:

```
[#s(hash-table size 2 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("method" "$/feedbackDismissAlert" "params" #s(hash-table size 2 test equal rehash-size 1.5 rehash-threshold 0.8125 data ("id" 71 "uri" "file:///home/lord/tmp/test.org"))))]
```

Which looks normal at the first glance. I will try to debug it further.

**Comment by jcs090218** [comment]
Sorry for the late reply!

I have opened an issue to the upstream, hopefully I will get something back. See https://github.com/znck/grammarly/issues/277.

**Comment by jcs090218** [comment]
The new language server in should resolve this issue! Please upgrade (reinstall) the language server to version `0.1.8`.
