### ISSUE TITLE
Grammarly authentication code

### ISSUE THREAD

**Issue by swarnendubiswas** [emacs-grammarly/lsp-grammarly#14]
I use `lsp-grammarly-login` and use VS Code or the browser to authenticate (PRO account). During this process. there is no CAPTCHA that shows up. However, Emacs minibuffer is stuck asking for `[Grammarly Authentication] code`. 

Please let me know where and how can I find the code and input to Emacs.

**Comment by jcs090218** [comment]
Please read the full section [here](https://github.com/emacs-grammarly/lsp-grammarly#money_with_wings-using-a-paid-grammarly-account).

**Comment by swarnendubiswas** [comment]
Thanks!
