### ISSUE TITLE
Not working out of the box

### ISSUE THREAD

**Issue by pati-ni** [emacs-grammarly/lsp-grammarly#15]
New user here and I seem to be having problems running grammarly through emacs.  I have grammarly premium which I have successfully authenticate but I don't think this makes a difference.

In a simple txt buffer I try to start LSP, and although the grammarly LSP spawns successfully, it fails with the following message:

> LSP :: Error from the Language Server: Request textDocument/hover failed with message: Array.from(...).flat is not a function (Internal Error)

In the lsp trace I can see this:

> [Trace - 04:13:46 PM] Sending request 'textDocument/hover - (1460)'.
> Params: {
>   "textDocument": {
>     "uri": "file:///home/main/tmp.txt"
>   },
>   "position": {
>     "line": 0,
>     "character": 49
>   }
> }
> 
> 
> [Trace - 04:13:46 PM] Received request '$/getToken - (1).
> Params: null
> 
> 
> [Trace - 04:13:46 PM] Sending response '$/getToken - (1)'. Processing request took 0ms
> Params: {
>   "jsonrpc": "2.0",
>   "id": 1,
>   "result": null
> }
> 
> 
> [Trace - 04:13:46 PM] Received response 'textDocument/codeAction - (1459)' in 53ms.
> Result: []
> 
> 
> [Trace - 04:13:46 PM] Received response 'textDocument/hover - (1460)' in 52ms.
> Result: {
>   "code": -32603,
>   "message": "Request textDocument/hover failed with message: Array.from(...).flat is not a function"
> }

and `grammarly-ls` throws the following exception:

> TypeError: Array.from(...).flat is not a function
>     at GrammarlyDiagnosticsService.sendDiagnostics (/usr/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/dist/index.cjs.js:1168:140)
>     at document.host.onDispose.watch (/usr/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/dist/index.cjs.js:1070:18)
>     at Object.job [as scheduler] (/usr/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/dist/index.cjs.js:774:13)
>     at run (/usr/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/node_modules/@vue/reactivity/dist/reactivity.cjs.js:187:28)
>     at Set.forEach (<anonymous>)
>     at trigger (/usr/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/node_modules/@vue/reactivity/dist/reactivity.cjs.js:193:13)
>     at RefImpl.set value [as value] (/usr/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/node_modules/@vue/reactivity/dist/reactivity.cjs.js:780:13)
>     at TextGrammarCheckHost.repositionAlerts (/usr/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/dist/index.cjs.js:543:27)
>     at TextGrammarCheckHost.setText (/usr/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/dist/index.cjs.js:525:14)
>     at GrammarlyClient.onConnection [as _onConnection] (/usr/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/dist/index.cjs.js:455:22)
> TypeError: Array.from(...).flat is not a function
>     at GrammarlyDiagnosticsService.sendDiagnostics (/usr/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/dist/index.cjs.js:1168:140)
>     at document.host.onDispose.watch (/usr/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/dist/index.cjs.js:1070:18)
>     at Object.job [as scheduler] (/usr/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/dist/index.cjs.js:774:13)
>     at run (/usr/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/node_modules/@vue/reactivity/dist/reactivity.cjs.js:187:28)
>     at Set.forEach (<anonymous>)
>     at trigger (/usr/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/node_modules/@vue/reactivity/dist/reactivity.cjs.js:193:13)
>     at Proxy.set$1 (/usr/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/node_modules/@vue/reactivity/dist/reactivity.cjs.js:436:9)
>     at EventEmitter.TextGrammarCheckHost.on (/usr/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/dist/index.cjs.js:475:31)
>     at EventEmitter.emit (events.js:182:13)
>     at Object.onMessage (/usr/lib/node_modules/@emacs-grammarly/unofficial-grammarly-language-server/dist/index.cjs.js:457:49)
> 

Is there a way to emulate if this is an lsp-grammarly emacs issue or it is language-server problem?

When I run this test it succeeds:
```
(require 'grammarly)

(defun test-on-message (data)
  "On message callback with DATA."
  (message "[DATA] %s" data))

;; Set callback for receiving data.
(add-to-list 'grammarly-on-message-function-list 'test-on-message)

(grammarly-check-text "I don't know what I area this. But Instead I am waiting for something to change.")
```

> [DATA] {"sid":1,"rev":0,"score":51,"generalScore":-1,"removed":[],"dialect":"american","foreign":false,"checksStatus":"all_checks_succeeded","action":"finished"}

Any ideas on where to find a working setup?

**Comment by pati-ni** [comment]
I solved it, I was using a different version of `node` that was loaded by my conda enviroment.

**Comment by jcs090218** [comment]
Cool! I was replying with confusions. Glad the problem is resolved! 👍 😄
