### ISSUE TITLE
automatic corrections

### ISSUE THREAD

**Issue by vzaliva** [emacs-grammarly/lsp-grammarly#17]
I am logged into my Grammarly account, but I could not figure out how to make corrections. For example, in Web interfaces when a comma is missing Grammarly suggests placing it for me. In Emacs LSP mode I only see a message about missing comma but not a suggestion or action to correct it. If there is a special key binding for this? Or perhaps it needs to be enabled?

**Comment by jcs090218** [comment]
This sounds like an upstream question, see https://github.com/emacs-lsp/lsp-mode/issues/353. I am using lsp-ui; hope this helps!

**Comment by jcs090218** [comment]
Close this issue for inactive reason! Feel free to reopen this issue if I didn't answer your question!

**Comment by lgmoneda** [comment]
Hi @jcs090218! I have the same question. I'm using lsp-ui, but it shows the hint, not the corrective action. I share @vzaliva's expectation that it would show the action to fix. In the "She go there", it wouldn't show only the explanation, but suggest "goes" or even enable to replace it by "goes" using a command.

**Comment by lgmoneda** [comment]
Hey @jcs090218, any hint on how to get the suggested correction within Emacs? Thanks

**Comment by jcs090218** [comment]
Try enable `lsp-ui-sideline`. You should able to see the code action from it.
