### ISSUE TITLE
grammarly error dialogue box showing login

### ISSUE THREAD

**Issue by HumHongeKamyaab** [emacs-grammarly/lsp-grammarly#19]
I have login into the premium Grammarly, still the lsp dialogue box on mouse hover over the error shows _login_ for automate fix,

![image](https://user-images.githubusercontent.com/19993444/130763100-ec7a260d-5f7f-4e7c-b6b7-cb9bde3c17a5.png)

**Comment by jcs090218** [comment]
Can you try evaluate the following snippet?

```el
(require 'keytar)
(message "%s" (keytar-get-password "vscode-grammarly-cookie" "default"))
```

You should able to see something like,

```
{\"isAnonymous\":false,\"isPremium\":true,\"token ...
```

**Comment by HumHongeKamyaab** [comment]
I am getting following in message buffer
```
keytar get-pass [service] [account]

Get the stored password for the `service` and `account`

Options:
      --version  Show version number                                   [boolean]
      --help     Show help                                             [boolean]
  -s, --service
  -a, --account

[Error: Error calling StartServiceByName for org.freedesktop.secrets: Timeout was reached]
```

my grammarly setup is
```elisp
      (use-package keytar
              :config
  (keytar-install)
    )
      (use-package lsp-grammarly
              :after keytar
        :hook (text-mode . (lambda ()
                             (require 'lsp-grammarly)
                             (lsp-deferred))))

```

**Comment by jcs090218** [comment]
> I am getting following in message buffer

Strange... it looks like you didn't login. Make sure you follow the guide in the README page. Hope it helps!

**Comment by HumHongeKamyaab** [comment]
I think the issue is the following
https://github.com/emacs-grammarly/lsp-grammarly/issues/18#issuecomment-905485531
just removed the other instance
