### ISSUE TITLE
Cannot ignore Grammarly issues

### ISSUE THREAD

**Issue by searene** [emacs-grammarly/lsp-grammarly#21]
When I try to ignore a Grammarly issue, I get the following error:

```
LSP :: `workspace/executeCommand' with `grammarly.callback' failed.

(error "The connected server(s) does not support method workspace/executeCommand.
To find out what capabilities support your server use ‘M-x lsp-describe-session’
and expand the capabilities section")
```

**Comment by searene** [comment]
Here is the process to reproduce the issue:

1. Type some nonsense, and execute `lsp-grammarly-check-grammar` to mark this error.
2. Execute `lsp-execute-code-action` and select `Ignore Grammarly Issue`
3. The error occurs, as shown above.

**Comment by vzaliva** [comment]
I am having the same problem. Very annoying.

**Comment by lbkvu** [comment]
Even when I select the suggested fix from Grammarly and press Enter, this error still happens. Very annoying!

**Comment by jcs090218** [comment]
The new language server in should resolve this issue! Please upgrade (reinstall) the language server to version `0.1.8`.
