### ISSUE TITLE
does not work in org-mode

### ISSUE THREAD

**Issue by vzaliva** [emacs-grammarly/lsp-grammarly#23]
I see the following warning:

```
Warning (lsp-mode): Unable to calculate the languageId for buffer ‘directions.org’. Take a look at ‘lsp-language-id-configuration’. The ‘major-mode’ is org-mode
```

And my document is not checked. It was working before. Current version is 20210715.918 from MELPA

**Comment by vzaliva** [comment]
My workaround was: `(add-to-list 'lsp-language-id-configuration '(org-mode . "plaintext"))`

I see org-mode mentioned in the source elsewhere. You may as well do something like this by default.

**Comment by jcs090218** [comment]
Sorry for the late reply.

> I see the following warning:

Interesting... I am not able to reproduce this warning and had start up the `lsp-grammarly` successfully. 

> (add-to-list 'lsp-language-id-configuration '(org-mode . "plaintext"))

Do you need this to start the language server, or it would just get rid of the warning? 😕

**Comment by vzaliva** [comment]
To start language server

**Comment by jcs090218** [comment]
> To start language server

hmmm... I can't reproduce this on my machine. It would allow me to start the language server in `org-mode` without any configuration.

**Comment by jcs090218** [comment]
Should fix in the upstream, see https://github.com/emacs-lsp/lsp-mode/pull/3235.

Thanks for reporting this issue to us!
