### ISSUE TITLE
lsp-grammarly in hard line-wrapped  sentences 

### ISSUE THREAD

**Issue by feng-li** [emacs-grammarly/lsp-grammarly#26]
First of all, very nice work with the `lsp` integration and the premium account setup. 

It seems that the current Grammarly setup treats a hard line-wrapped sentence into two sentences. 
![Screenshot from 2022-03-18 17-45-49](https://user-images.githubusercontent.com/1174311/158994476-c7ba666e-6042-488b-82df-199d2692c543.png)

Is it possible to have an option to allow for it?

1. Multiple white spaces and a single line break are the same as a single space.
2. Multiple line breaks indicate different sentences.

**Comment by jcs090218** [comment]
Sorry for the late reply.

Can you try the new server? They have now used the tree-sitter to parse markdown; hence this issue should be resolved or at least gotten better.

**Comment by feng-li** [comment]
Seems resolved with the updated version. Thanks a lot!

**Comment by jcs090218** [comment]
I guess this can be closed now? Thanks! ❤️
