### ISSUE TITLE
error message upon selecting correction action

### ISSUE THREAD

**Issue by eli-tziperman** [emacs-grammarly/lsp-grammarly#29]
Hi, when I select a code action for correcting a grammarly mistake, the mistake is corrected but I then I get the error below.  This happens when I use the lsp-ui package with sideline activated, or when calling code actions using the lsp right-click menu.  I am using GNU Emacs 27.2 (aarch64-apple-darwin20.6.0, Carbon Version 164 AppKit 2022.6). Thanks...

Debugger entered--Lisp error: (error "The connected server(s) does not support method workspace/executeCommand.\nTo find out what capabilities support your server use ‘M-x lsp-describe-session’\nand expand the capabilities section")
  signal(error ("The connected server(s) does not support method workspace/executeCommand.\nTo find out what capabilities support your server use ‘M-x lsp-describe-session’\nand expand the capabilities section"))
  error("The connected server(s) does not support method %s.\nTo find out what capabilities support your serve..." "workspace/executeCommand")
  lsp--send-request-async((:jsonrpc "2.0" :method "workspace/executeCommand" :params (:command "grammarly.callback" :arguments [#<hash-table equal 2/2 XX>])) #f(compiled-function (res) #<bytecode XX>) detached #f(compiled-function (err) #<bytecode 0xba3915a5>) nil nil :sync-request)
  lsp-request-async("workspace/executeCommand" (:command "grammarly.callback" :arguments [#<hash-table equal 2/2 XX>]) #f(compiled-function (res) #<bytecode XX>) :error-handler #f(compiled-function (err) #<bytecode XX>) :no-merge nil :mode detached :cancel-token :sync-request)
  lsp-request("workspace/executeCommand" (:command "grammarly.callback" :arguments [#<hash-table equal 2/2 XX>]))
  lsp-workspace-command-execute("grammarly.callback" [#<hash-table equal 2/2 XX>])
  lsp-send-execute-command("grammarly.callback" [#<hash-table equal 2/2 XX>])
  lsp--execute-command(#<hash-table equal 3/3 XX>)
  lsp--execute-code-action(#<hash-table equal 6/6 XX>)
  lsp-execute-code-action(#<hash-table equal 6/6 XX>)
  #f(compiled-function () (interactive nil) #<bytecode XX>)()
  funcall-interactively(#f(compiled-function () (interactive nil) #<bytecode XX>))
  call-interactively(#f(compiled-function () (interactive nil) #<bytecode XX>) nil nil)
  command-execute(#f(compiled-function () (interactive nil) #<bytecode XX>))

**Comment by jcs090218** [comment]
Sorry for the late reply.

I think this issue is from the old server, can you try the new one? Thanks!

**Comment by jcs090218** [comment]
Awesome! I guess the issue can be closed now! 😄 Thanks!
