### ISSUE TITLE
Grammarly premium instructions

### ISSUE THREAD

**Issue by innerout** [emacs-grammarly/lsp-grammarly#3]
Hello,
Thanks for adding Grammarly support in Emacs! Since the znck/grammarly repo supports Grammarly premium, could you provide some instructions in the README on how someone could login and use the paid features?

**Comment by jcs090218** [comment]
Sorry for the late reply. 

I am working on the premium login with #4. I would still need some work for it. Please stay tuned! :D

**Comment by innerout** [comment]
Thanks for the answer, take your time this plugin is already great but with the premium features, it is going to be awesome!

**Comment by jcs090218** [comment]
I have merged the PR #4. Let me know if the document works for you! :)

Feel free to send PR to revise the document if needed!
