### ISSUE TITLE
(lsp-grammarly-login) is generating a `redirect_uri` of `[object+Object]`.

### ISSUE THREAD

**Issue by eihli** [emacs-grammarly/lsp-grammarly#38]
When I run `(lsp-grammarly-login)`, my browser opens to grammarly.com https://www.grammarly.com/signin/app/consent?..normal-looking-stuff...&redirect_uri=%5Bobject+Object%5D

I haven't been able to track down why.

`├── @emacs-grammarly/grammarly-languageserver@0.1.8`
`  lsp-grammarly                  20220704.626   available    melpa    LSP Clients for Grammarly`

![image](https://user-images.githubusercontent.com/1719584/177218341-4e8bc680-bdbf-4feb-8566-abfd7af17548.png)

**Comment by jcs090218** [comment]
Sorry, the Emacs login implementation for new language server is still WIP. There is a warning mark under the [method 2...](https://github.com/emacs-grammarly/lsp-grammarly#-method-2-login-with-emacs-a-bit-complicated) header section

Please discuss this in #35.
