### ISSUE TITLE
A question about ignoring errors

### ISSUE THREAD

**Issue by searene** [emacs-grammarly/lsp-grammarly#43]
Hi! Thanks for creating this amazing plugin! I've been using it and I really like it! However, I'm a little confused about ignoring an error. Suppose I write the following sentence in a file in Emacs:

```
This is boy.
```

`lsp-grammarly` will tell me that an article is missing. That's right. But I want to ignore this error. So I move the cursor to the word `boy` and execute `lsp-execute-code-action`, then I get two options:

1. Add an article - a
2. Dismiss - Add an article

What does it mean if I choose the second option? I have several guesses:

1. `lsp-grammarly` will never mark the missing article as an error **in any file**.
2. `lsp-grammarly` will never mark the missing article as an error **in the current file**.
3. `lsp-grammarly` will never mark the missing article as an error **in the current sentence**.

Which one is correct? Thanks in advance.

**Comment by jcs090218** [comment]
Hi, Searene! Thanks for using this package! ❤️ 

> What does it mean if I choose the second option? I have several guesses:

The answer is 2. But once you have dismissed the current session, it will remain back up. Hope this answer helps! :)

**Comment by searene** [comment]
> 

Got it, thanks :)

**Comment by searene** [comment]
> Hi, Searene! Thanks for using this package! ❤️
> 
> > What does it mean if I choose the second option? I have several guesses:
> 
> The answer is 2. But once you have dismissed the current session, it will remain back up. Hope this answer helps! :)

Got it, thanks :)
