### ISSUE TITLE
Add support for emails with mu4e

### ISSUE THREAD

**Issue by Gavinok** [emacs-grammarly/lsp-grammarly#44]
Allow lsp to start when composing emails with mu4e

**Comment by jcs090218** [comment]
There are three variables control the LSP services.

1. project root must be defined
2. `lsp-grammarly-active-modes`
3. `lsp-grammarly-patterns`

I think once these requirements are met, you should able to run [lsp-grammarly]() in those buffers. Hope the information helps! ❤️

**Comment by jcs090218** [comment]
Another choice is to use [flycheck-grammarly](https://github.com/emacs-grammarly/flycheck-grammarly) or [flymake-grammarly](https://github.com/emacs-grammarly/flymake-grammarly) (`flycheck` vs `flymake`), and these packages aren't LSP base so those requirements can be ignored.

**Comment by Gavinok** [comment]
Thanks!
