### ISSUE TITLE
Any suggestions for mu4e-compose-mode?

### ISSUE THREAD

**Issue by bridgesense** [emacs-grammarly/lsp-grammarly#45]
I'd love to get this working with mu4e.  

I'm using the following hook:
  (add-hook 'mu4e-compose-mode-hook
            (lambda ()
              (require 'lsp-grammarly)
              (lsp-deferred)))

I get the error: 

Warning (lsp-mode): Unable to calculate the languageId for buffer ‘*draft*’. Take a look at ‘lsp-language-id-configuration’. The ‘major-mode’ is mu4e-compose-mode

Do I try to trick lsp into treating mu4e-compose-mode like org-mode?  Any suggestions on how I might get this to work?

**Comment by jcs090218** [comment]
Please see #44!

**Comment by bridgesense** [comment]
Thanks.

That worked.  I had to enter the following lines to work with LSP.

```
  (setq lsp-grammarly-active-modes '(text-mode latex-mode org-mode markdown-mode mu4e-compose-mode))
  (with-eval-after-load 'lsp-mode
    (add-to-list 'lsp-language-id-configuration
                 '(mu4e-compose-mode . "text")))
  (add-hook 'mu4e-compose-mode-hook
            (lambda ()
              (require 'lsp-grammarly)
              (lsp-deferred)))
```

**Comment by jcs090218** [comment]
Awesome! I think this issue can be closed now? :)

**Comment by bridgesense** [comment]
I had to dump spacemacs due to some other nagging issues. Interestingly enough, the fix I employed above no longer works.

I looked through the spacemacs environment setup for mu4e and I didn't notice anything different than what I have currently employed.

If anyone else has mu4e-compose-mode working with lsp-grammarly, would you mind sharing your setup?

Thanks!

**Comment by jcs090218** [comment]
@bridgesense Can you see if this help? See https://github.com/emacs-grammarly/lsp-grammarly/issues/44#issuecomment-1271312145.

**Comment by bridgesense** [comment]
I had tried that before, and it didn't work. I was using use-package and  setting the lsp-grammarly-active-modes under config.

I moved the setq line under :init, and it works!  Thanks!
