### ISSUE TITLE
How to get popup with description of grammatical error

### ISSUE THREAD

**Issue by FlyingSamson** [emacs-grammarly/lsp-grammarly#47]
Hey there,

thank you for this awesome plugin.

A slightly of-topic question: What plugin/configuration did you use to produce the screenshot in the readme. To be more specific, how did you get this popup showing what I assume is the response of `lsp-describe-thing-at-point`?

Thank you for any help!

**Comment by jcs090218** [comment]
That is from awesome package [lsp-ui](https://github.com/emacs-lsp/lsp-ui) created by `@sebastiencs`.

Here are commands that you can use, https://github.com/emacs-lsp/lsp-ui/blob/master/lsp-ui-doc.el#L1167-L1196.
