### ISSUE TITLE
Warning (lsp-mode): Unknown request method: $/updateDocumentState

### ISSUE THREAD

**Issue by nasyxx** [emacs-grammarly/lsp-grammarly#5]
There are lots of these warnings.  Is this the wrong method?

**Comment by jcs090218** [comment]
Hi, the warning is from language server trying to update the client's status bar (VSCode). This is currently on the roadmap for now, see [here](https://github.com/emacs-grammarly/lsp-grammarly/tree/client#pencil-roadmap). Right now the message should not do anything to Emacs. Hope this answers your question! :)

**Comment by nasyxx** [comment]
Thanks!

**Comment by jcs090218** [comment]
I have implemented the callback hence the warning should not be shown anymore. :)

Close this now.
