### ISSUE TITLE
emacs does not complete initialization, stalled; emacs 29.1 and doom

### ISSUE THREAD

**Issue by sm101** [emacs-grammarly/lsp-grammarly#59]
OSX Ventura
emacs 29.1 (brew emacs plus)

a) I added into doom emacs config.el:

(use-package lsp-grammarly
  :ensure t
  :hook (text-mode . (lambda ()
                       (require 'lsp-grammarly)
                       (lsp))))  ; or lsp-deferred

Recreated doom configuration
b) Connected my paid Grammarly account to vscode

Emacs now does not complete initialization and show white window with no minibufer.

**Comment by jcs090218** [comment]
It sounds strange. Are there any error messages, backtrace log, etc? 🤔 It doesn't sound like the issue from this package though!

**Comment by sm101** [comment]
I pulled trigger too early. It does not have anything to do with this package. I apologize for wasting your time.
