### ISSUE TITLE
Random mistakes that don't appear in the Browser

### ISSUE THREAD

**Issue by jcubic** [emacs-grammarly/lsp-grammarly#64]
Got weird messages:

![Przechwycenie obrazu ekranu_2024-02-22_02-15-49](https://github.com/emacs-grammarly/lsp-grammarly/assets/280241/5916f15d-4d8a-480a-ba73-dbf917f91e22)

I don't understand what it means, what are agreements?

The browser only reports "is" to correct as "are", the errors doesn't make sense:

![Przechwycenie obrazu ekranu_2024-02-22_02-17-33](https://github.com/emacs-grammarly/lsp-grammarly/assets/280241/5fb7c679-c18a-4b6c-82da-98ae84c3b66e)

Another issue is that company is not working at all. `M-x company-diag` shows backend: `company-dabbrev`. I need to call this function manually and most of the time it gives error:

> company-begin-backend: Cannot complete at point

The only way I can get company mode is between the lines that give this output:

![Przechwycenie obrazu ekranu_2024-02-22_02-42-27](https://github.com/emacs-grammarly/lsp-grammarly/assets/280241/fed5397c-30b9-45ff-93f3-557b24fd1f92)

**Comment by jcs090218** [comment]
> I don't understand what it means, what are agreements?

Try show doc, see:

![2024-02-21 17 48 19](https://github.com/emacs-grammarly/lsp-grammarly/assets/8685505/f74c59c7-3466-4547-aac9-c2d308fbf37d)

Change it to `forms` to fix this issue.

> The only way I can get company mode is between the lines that give this output:

I have these questions:

1. What do you expect from company mode since you are in a text-mode buffer. 🤔 What are you completing?
2. It seems like a misconfiguration from `lsp-mode`. You might want to take a look at their homepage https://emacs-lsp.github.io/lsp-mode/.

**Comment by jcubic** [comment]
Can you explain how to configure lsp-mode so your library works as it should? I don't see any configuration information on the lsp-mode website, there is one tutorial that only shows how to disable stuff that should be enabled by default.

What I would expect is that company mode allows to fix spelling mistakes.

What do you mean by "Try show doc" how to show doc? Do I need to manually trigger it? I don't see any information about this in the README. If this is required I would add it to docs.

The docs only say `(lsp)`.

**Comment by jcubic** [comment]
Never mind, it seems something is broken and I have no idea how to fix it, and there is information on how to use your project with lsp-mode. Will use the browser instead.

**Comment by jcs090218** [comment]
> Can you explain how to configure lsp-mode so your library works as it should? I don't see any configuration information on the lsp-mode website, there is one tutorial that only shows how to disable stuff that should be enabled by default.

`lsp-mode` is a LSP implementation in elisp, see https://emacs-lsp.github.io/lsp-mode/page/main-features/. `lsp-mode` has features that are "good enough" to use. I'm guessing, you are missing the [lsp-ui](https://github.com/emacs-lsp/lsp-ui) which gives you the doc frame (the screenshot above). `lsp-ui`  will give you most advanced features from `lsp-mode`. 

> What I would expect is that company mode allows to fix spelling mistakes.

No, `company-mode` doesn't do that. What you need is the code action library (see [LSP spec](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/) for knowing more about code action). The code action implementation is in `lsp-ui` and it's called `lsp-ui-sideline`. Another option for even more advanced users is [sideline](https://github.com/emacs-sideline/sideline) + [sideline-lsp](https://github.com/emacs-sideline/sideline-lsp) (this is the one I'm using).

> What do you mean by "Try show doc" how to show doc? Do I need to manually trigger it? I don't see any information about this in the README. If this is required I would add it to docs.

Sorry for the confusion. I assumed you are using some kind of lsp frontend packages. The show doc feature is in `lsp-ui`.

> Never mind, it seems something is broken and I have no idea how to fix it, and there is information on how to use your project with lsp-mode. Will use the browser instead.

Sorry to hear that. Emacs has a very hard learning curve, and `lsp-mode` isn't very easy to configure (the correct way). There are other options like, 

- [flycheck-grammarly](https://github.com/emacs-grammarly/flycheck-grammarly) (this is what I used before `lsp-grammarly`)
- [flymake-grammarly](https://github.com/emacs-grammarly/flymake-grammarly)
- [eglot-grammarly](https://github.com/emacs-grammarly/eglot-grammarly) (eglot is another lsp implementation; but I don't know if it would be any easier than `lsp-mode` 🤔)

Please ask me any questions. I would like to help. :)

**Comment by jcubic** [comment]
Thanks for the tips, will check lsp-ui and fylecheck-grammarly.
