### ISSUE TITLE
grammarly-lsp not working in AUCtex

### ISSUE THREAD

**Issue by eli-tziperman** [emacs-grammarly/lsp-grammarly#66]
Hi, grammarly-lsp stopped working in latex files when I upgraded to AUCtex 14; perhaps this is related to https://github.com/emacs-lsp/lsp-mode/issues/4332 ? Not sure where this needs to be addressed, so am mentioning it here just in case, cheers.

**Comment by jcs090218** [comment]
I think this related to https://github.com/emacs-languagetool/lsp-ltex/pull/41?

Can you try adding `LaTeX-mode` to `lsp-grammarly-active-modes`?

**Comment by eli-tziperman** [comment]
That helped! thank you

**Comment by jcs090218** [comment]
Feel free to open a PR to set these variables as the default. ;)

**Comment by eli-tziperman** [comment]
If I only knew how to... 🌹 thanks again, though!
