### ISSUE TITLE
I can't get it to work in Emacs

### ISSUE THREAD

**Issue by agzam** [emacs-grammarly/lsp-grammarly#7]
I've tried following instructions. 
I got keytar installed, etc.
In the beginning I've struggled quite a bit with the logging in, then it seemed like I've figured it out.
Now I can't get it to work neither in anonymous mode nor with a paid Grammarly account.

So I would run `lsp-grammarly-login`, follow the steps, get the callback url and it would say: `[INFO] Logged in as ‘Ag‘`,
but once I'm in a text buffer, it would do the following:

```
LSP :: grammarly-ls has exited (killed: 9)
LSP :: Restarting LSP in buffer something.txt
LSP :: Connected to [grammarly-ls:84308/starting].
[INFO] Visited as, anonymous
LSP :: grammarly-ls:84308 initialized successfully
```
And I'm no longer "logged in". And when I call `lsp-grammarly-check-grammar` it would just say: `Start Grammarly checker...` but nothing actually happens. And there's nothing in `*grammarly-ls*` or `*grammarly-ls::stderr*`, `*lsp-log*` buffer has:

```
Command "/Users/ag/.emacs-profiles/.emacs-spacemacs.d/.cache/lsp/npm/@emacs-grammarly/unofficial-grammarly-language-server/bin/unofficial-grammarly-language-server --stdio" is present on the path.
Command "/Users/ag/.emacs-profiles/.emacs-spacemacs.d/.cache/lsp/npm/@emacs-grammarly/unofficial-grammarly-language-server/bin/unofficial-grammarly-language-server --stdio" is present on the path.
Found the following clients for /Users/aibragim/sandbox/something.txt: (server-id grammarly-ls, priority -1)
The following clients were selected based on priority: (server-id grammarly-ls, priority -1)
```

I'm using Emacs 28.0.50 in OS X Big Sur.

Btw. It works in VS Code. But I would like to use it in Emacs.

**Comment by jcs090218** [comment]
Try restart Emacs, once you have logged in then it should be logged in unless you called `M-x lsp-grammarly-logout` or you accidentally remove credential by other actions.

To check your credential exists, try the following command in the terminal.

```sh
keytar get-pass -s vscode-grammarly-cookie -a default
```

It should print out a json with your credential information.

**Comment by agzam** [comment]
Whoa, I have finally figured it out. Apparently, my issue was related to the previous one here []. Basically, I needed to make sure that I logged in with VS Code as well, even though I was using the callback URL in Emacs.

This thing works beautifully. It took me some time to figure it out, and at some point, I got so frustrated that I started feeling a bit skeptical. But it works! I can only imagine the possibilities. Thank you for making this possible. I like Grammarly, but I hate their app. I don't want their stupid editor. I am already using the best tool in the world for text-manipulation. Why would I use anything else?

**Comment by agzam** [comment]
Honestly, I was so surprised to see that even lsp-code-actions work. I would misspell a word or do something stupid, and lsp-code-action would use Grammarly's suggestion and fix it. Although, it looks like "Ignore Grammarly Issue" doesn't work.

**Comment by jcs090218** [comment]
> Although, it looks like "Ignore Grammarly Issue" doesn't work.

Ah, yes. I have not got time to implement this feature yet. I would place this on the road map.

**Comment by benthamite** [comment]
It took me quite a bit of time to get `lsp-grammarly` to work, so in case it helps others I'm copying my working config below. (I landed here after searching for `Start Grammarly checker...` while searching for potential solutions, so I figured posting here makes the code more discoverable for those who may benefit from it.)

``` emacs-lisp
(use-package keytar
  :ensure-system-package
  (keytar . "sudo npm install -g @emacs-grammarly/keytar-cli"))

(use-package lsp-grammarly
  :after keytar
  :ensure-system-package
  (unofficial-grammarly-language-server . "sudo npm i -g @emacs-grammarly/unofficial-grammarly-language-server")
  :hook (text-mode . (lambda ()
                       (require 'lsp-grammarly)
                       (lsp))))
```

(For `:ensure-system-package` to work, the package `use-package-ensure-system-package` needs to be installed.)

I had installed both of those dependencies manually, so I'm not sure why it only worked after requiring them as part of the 
`use-package`declaration.

**Comment by jcs090218** [comment]
For `keytar`, you can do `M-x keytar-install`. Make sure you have sudo permission.

For `lsp-grammarly`, you should able to see the language server as a download option after you opened a text file. Or call `M-x lsp-install-server`.
