### ISSUE TITLE
Implement "Ignore Grammarly Issue" code action

### ISSUE THREAD

**Issue by agzam** [emacs-grammarly/lsp-grammarly#9]
in Emacs, when there are multiple errors, and (for example) the first one is considered a typo (which the user chooses to ignore, let's say if it's some acronym) and the second one is an honest mistake that could be fixed using a code action. That, as it turns out, not possible, because trying to execute a code action for the error at-point, would prompt for the first mistake, and not the second, even if the point is at the second.

Expected: The code action prompt for the second mistake. I'm not sure if this is a bug in the package or this is due to implementation in lsp-mode. Either way, there should be a way to mark errors to be ignored - so the user can ignore the first one and fix the second one. There's a code action for that, but it currently doesn't work.

**Comment by jcs090218** [comment]
Sorry for the late reply!

I think this is caused by #11. Let's move the discussion over there!

**Comment by jcs090218** [comment]
The new language server should resolve this issue! Please upgrade (reinstall) the language server to version `0.1.8`.

**Comment by agzam** [comment]
OMG, early Christmas. Thank you so much for fixing this. It's been the main (and perhaps the only) annoyance in my daily usage of this awesome package. I can't appreciate you enough for taking care of this.

**Comment by jcs090218** [comment]
My pleasure. ❤️
